module.exports = {
  "PGNs": [
    {
        "PGN":126720,
        "Id":"signalkOverN2kUpdate",
        "Description":"SignalK Over N2K Update",
        "Type":"Fast",
        "Complete":true,
        "Length":15,
        "RepeatingFields":0,
        "Fields":[
          {
            "Order":1,
            "Id":"manufacturerCode",
            "Name":"Manufacturer Code",
            "Description":"SignalK",
            "BitLength":11,
            "BitOffset":0,
            "BitStart":0,
            "Match":999,
            "Type":"Manufacturer code",
            "Signed":false},
          {
            "Order":2,
            "Id":"reserved",
            "Name":"Reserved",
            "BitLength":2,
            "BitOffset":11,
            "BitStart":3,
            "Resolution":0,
            "Signed":false},
          {
            "Order":3,
            "Id":"industryCode",
            "Name":"Industry Code",
            "Description":"Marine Industry",
            "BitLength":3,
            "BitOffset":13,
            "BitStart":5,
            "Match":4,
            "Type":"Lookup table",
            "Signed":false},
          {
            "Order":4,
            "Id":"proprietaryId",
            "Name":"Proprietary ID",
            "Description":"Update",
            "BitLength":16,
            "BitOffset":16,
            "BitStart":0,
            "Match":1,
            "Type":"Integer",
            "Resolution":1,
            "Signed":false},
          {
            "Order":5,
            "Id":"context",
            "Name":"Context",
            "BitLength":128,
            "BitOffset":32,
            "BitStart":0,
            "Type":"ASCII or UNICODE string starting with length and control byte",
            "Signed":false},
          {
            "Order":6,
            "Id":"sourceid",
            "Name":"SourceId",
            "BitLength":128,
            "BitStart":0,
            "Type":"ASCII or UNICODE string starting with length and control byte",
            "Signed":false},
          {
            "Order":7,
            "Id":"path",
            "Name":"Path",
            "BitLength":128,
            "BitStart":0,
            "Type":"ASCII or UNICODE string starting with length and control byte",
            "Signed":false},
          {
            "Order":8,
            "Id":"value",
            "Name":"Value",
            "BitLength":128,
            "BitStart":0,
            "Type":"ASCII or UNICODE string starting with length and control byte",
            "Signed":false}]},
      {
        "PGN":126720,
        "Id":"signalkOverN2kMeta",
        "Description":"SignalK Over N2K Meta",
        "Type":"Fast",
        "Complete":true,
        "Length":15,
        "RepeatingFields":0,
        "Fields":[
          {
            "Order":1,
            "Id":"manufacturerCode",
            "Name":"Manufacturer Code",
            "Description":"SignalK",
            "BitLength":11,
            "BitOffset":0,
            "BitStart":0,
            "Match":999,
            "Type":"Manufacturer code",
            "Signed":false},
          {
            "Order":2,
            "Id":"reserved",
            "Name":"Reserved",
            "BitLength":2,
            "BitOffset":11,
            "BitStart":3,
            "Resolution":0,
            "Signed":false},
          {
            "Order":3,
            "Id":"industryCode",
            "Name":"Industry Code",
            "Description":"Marine Industry",
            "BitLength":3,
            "BitOffset":13,
            "BitStart":5,
            "Match":4,
            "Type":"Lookup table",
            "Signed":false},
          {
            "Order":4,
            "Id":"proprietaryId",
            "Name":"Proprietary ID",
            "Description":"Meta",
            "BitLength":16,
            "BitOffset":16,
            "BitStart":0,
            "Match":2,
            "Type":"Integer",
            "Resolution":1,
            "Signed":false},
          {
            "Order":5,
            "Id":"context",
            "Name":"Context",
            "BitLength":128,
            "BitOffset":32,
            "BitStart":0,
            "Type":"ASCII or UNICODE string starting with length and control byte",
            "Signed":false},
          {
            "Order":6,
            "Id":"sourceid",
            "Name":"SourceId",
            "BitLength":128,
            "BitStart":0,
            "Type":"ASCII or UNICODE string starting with length and control byte",
            "Signed":false},
          {
            "Order":7,
            "Id":"path",
            "Name":"Path",
            "BitLength":128,
            "BitStart":0,
            "Type":"ASCII or UNICODE string starting with length and control byte",
            "Signed":false},
          {
            "Order":8,
            "Id":"value",
            "Name":"Value",
            "BitLength":128,
            "BitStart":0,
            "Type":"ASCII or UNICODE string starting with length and control byte",
            "Signed":false}]}
  ]
}
